Repository nitmic/nitmic.club.nitech.ac.jp, pull requests merged in 2025-04, with the labels that each got.

#203 ✨ Update repository name
  README.md
  go.mod
Labels: enhancement

#202 Delete package-lock.json
  package-lock.json
Labels: bug

#204 Dev Container を推奨するように README を修正
  README.md
Labels: documentation

#216 config.toml の social ブロックの冗長な記法の修正
  config.toml
Labels: enhancement

#228 Remove unused gallery images
  static/images/gallery/Arceus.png
  static/images/gallery/arceus_team.png
  static/images/gallery/banner.png
Labels: invalid

#238 Update fjktkm icon
  static/images/members_icon/2021/fjktkm.png
Labels: enhancement
